import hashlib
import json
import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, Mapping, Optional

from .catalog import ReleaseCatalog, validate_manifest_against_catalog
from .errors import PersonaForgeContractError
from .manifest import NormalizedManifest


class BuildContractError(PersonaForgeContractError):
    """The selected persona cannot produce an unambiguous build contract."""


@dataclass(frozen=True)
class BuildContract:
    build_key: str
    settings: Mapping[str, str]
    plan: Mapping[str, object]


def _generator_digest(generator_path: Path) -> str:
    return hashlib.sha256(generator_path.read_bytes()).hexdigest()


def resolve_build_contract(
    manifest: NormalizedManifest,
    catalog: ReleaseCatalog,
    source_commit: str,
    platform: str,
    generator_path: Path,
) -> BuildContract:
    validate_manifest_against_catalog(manifest, catalog)
    if manifest.name != Path(manifest.source).stem:
        raise BuildContractError("profile filename must match metadata.name")
    if not re.fullmatch(r"[0-9a-f]{40}", source_commit):
        raise BuildContractError("source commit must be a 40-character lowercase SHA-1")
    components = catalog.document["components"]
    required = set()
    for capability in manifest.document["capabilities"]["require"]:
        required.update(catalog.document["capabilities"][capability])

    settings: Dict[str, str] = {}
    decisions = []
    for capability in manifest.document["capabilities"]["omit"]:
        for component_name in catalog.document["capabilities"][capability]:
            component = components[component_name]
            variable = component.get("buildVariable")
            if component_name in required or component["protected"]:
                outcome, reason = "retained", "required or protected"
            elif variable:
                settings[variable] = "n"
                outcome, reason = "omitted", "catalog build variable"
            else:
                outcome, reason = "unsupported", "no build control in the 202605 catalog"
            decisions.append({
                "capability": capability,
                "component": component_name,
                "outcome": outcome,
                "reason": reason,
            })

    by_feature = {
        component.get("featureName"): (name, component)
        for name, component in components.items()
        if component.get("featureName")
    }
    for feature, state in manifest.document["overrides"]["features"].items():
        component_name, component = by_feature[feature]
        variable = component.get("buildVariable")
        if state != "default" and variable:
            settings[variable] = "y" if state == "enabled" else "n"
            decisions.append({
                "component": component_name,
                "outcome": "enabled" if state == "enabled" else "omitted",
                "reason": "explicit feature override",
            })

    if manifest.document["build"]["reduceFilesystem"]:
        variable = catalog.document["buildSettings"]["reduceFilesystem"]
        settings[variable] = "y"

    identity = {
        "catalogSha256": catalog.sha256,
        "generatorSha256": _generator_digest(generator_path),
        "manifestSha256": manifest.sha256,
        "platform": platform,
        "settings": dict(sorted(settings.items())),
        "sourceCommit": source_commit,
    }
    canonical_identity = json.dumps(identity, sort_keys=True, separators=(",", ":")).encode("utf-8")
    build_key = hashlib.sha256(canonical_identity).hexdigest()
    plan = {
        "schemaVersion": 1,
        "profile": manifest.name,
        "identity": identity,
        "decisions": sorted(decisions, key=lambda item: (item.get("component", ""), item.get("capability", ""))),
    }
    return BuildContract(build_key, dict(sorted(settings.items())), plan)


_MAKE_ASSIGNMENT = re.compile(r"^\s*(?:override\s+)?([A-Z][A-Z0-9_]*)\s*(?:\?|\+|:)?=\s*([^#]*?)\s*$")


def validate_config_user(path: Optional[Path], settings: Mapping[str, str]) -> None:
    if path is None or not path.exists():
        return
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        match = _MAKE_ASSIGNMENT.match(line)
        if not match or match.group(1) not in settings:
            continue
        variable, value = match.groups()
        if value != settings[variable]:
            raise BuildContractError(
                "{}:{} conflicts with persona setting {}={}".format(path, line_number, variable, settings[variable])
            )


def render_makefile(contract: BuildContract) -> str:
    lines = [
        "# Generated by scripts/personaforge-build; do not edit.",
        "PERSONAFORGE_BUILD_KEY := {}".format(contract.build_key),
    ]
    for variable, value in contract.settings.items():
        lines.extend([
            "ifneq ($(filter command line environment override,$(origin {})),)".format(variable),
            "ifneq ($({}),{})".format(variable, value),
            "$(error {}=$({}) conflicts with PersonaForge value {})".format(variable, variable, value),
            "endif",
            "endif",
            "{} = {}".format(variable, value),
        ])
    return "\n".join(lines) + "\n"


def atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=".{}-".format(path.name), dir=str(path.parent))
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def write_build_outputs(
    output_dir: Path,
    contract: BuildContract,
    manifest: NormalizedManifest,
    catalog: ReleaseCatalog,
) -> None:
    outputs = {
        "personaforge.mk": render_makefile(contract).encode("utf-8"),
        "manifest.normalized.json": manifest.canonical_json + b"\n",
        "catalog.json": catalog.canonical_json + b"\n",
        "build-plan.json": json.dumps(contract.plan, sort_keys=True, indent=2).encode("utf-8") + b"\n",
        "input.json": json.dumps(contract.plan["identity"], sort_keys=True, indent=2).encode("utf-8") + b"\n",
    }
    for name, content in outputs.items():
        atomic_write(output_dir / name, content)
